name: "Setup go-jsonnet"
description: "Download and install go-jsonnet with caching"
inputs:
  version:
    description: "go-jsonnet version to install"
    required: true
runs:
  using: "composite"
  steps:
    - name: Cache go-jsonnet
      id: cache-go-jsonnet
      uses: actions/cache@6849a6489940f00c2f30c0fb92c6274307ccb58a # v4.1.2
      with:
        path: /usr/local/bin/jsonnet*
        key: go-jsonnet-${{ inputs.version }}-${{ runner.os }}

    - name: Install go-jsonnet
      if: steps.cache-go-jsonnet.outputs.cache-hit != 'true'
      shell: bash
      run: |
        echo "Installing go-jsonnet ${{ inputs.version }}..."
        if [[ "${{ runner.os }}" == "Linux" ]]; then
          ARCH="Linux_x86_64"
        else
          echo "Unsupported OS: ${{ runner.os }}"
          exit 1
        fi

        wget -q https://github.com/google/go-jsonnet/releases/download/v${{ inputs.version }}/go-jsonnet_${{ inputs.version }}_${ARCH}.tar.gz
        tar -xzf go-jsonnet_${{ inputs.version }}_${ARCH}.tar.gz
        sudo mv jsonnet jsonnetfmt /usr/local/bin/
        rm go-jsonnet_${{ inputs.version }}_${ARCH}.tar.gz

        echo "go-jsonnet installed successfully"
        jsonnet --version
